apiVersion: v1
kind: Pod
metadata:
  labels:
    app: preset-test-pod
  name: preset-test-pod
spec:
  enableServiceLinks: false
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: preset-test-pod-nginx
      ports:
        - containerPort: 8080
          protocol: TCP
